import 'package:flutter/foundation.dart' show LicenseEntryWithLineBreaks, LicenseRegistry;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform, kIsWeb;

import 'core/design/app_theme.dart';
import 'utils/page_transitions.dart';

// Import screen files
import 'screens/auth_gate.dart';

// Make sure you have this file generated by the FlutterFire CLI
import 'firebase_options.dart';

/// App theme from DESIGN.md, with the app's page transitions.
ThemeData createAppTheme() {
  return AppTheme.light().copyWith(
    pageTransitionsTheme: const PageTransitionsTheme(
      builders: {
        TargetPlatform.android: AppPageTransition(),
        TargetPlatform.iOS: AppPageTransition(),
      },
    ),
  );
}

/// Bundled fonts are SIL OFL 1.1; surface their licenses in the About page.
void _registerFontLicenses() {
  LicenseRegistry.addLicense(() async* {
    for (final (family, file) in const [
      ('Inter', 'assets/fonts/Inter-OFL.txt'),
      ('Noto Sans Malayalam', 'assets/fonts/NotoSansMalayalam-OFL.txt'),
    ]) {
      yield LicenseEntryWithLineBreaks([family], await rootBundle.loadString(file));
    }
  });
}

void main() async {
  // Ensure Flutter bindings are initialized
  WidgetsFlutterBinding.ensureInitialized();
  _registerFontLicenses();

  // Initialize Firebase only on supported platforms (Android, iOS, Web)
  // Windows doesn't have Firebase C++ SDK support in current Flutter version
  if (kIsWeb ||
      defaultTargetPlatform == TargetPlatform.android ||
      defaultTargetPlatform == TargetPlatform.iOS) {
    await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform);
  }

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'AumLux',
      theme: createAppTheme(),
      debugShowCheckedModeBanner: false,
      // AuthGate handles reactive auth state and navigates to the correct screen
      home: const AuthGate(),
    );
  }
}
